# bot settings
settings = {
    # discord configs
    "token": "",  # token
    "bot": "",  # bot name
    # vk for auto horo
    'vklogin': 79123456789,
    'vkpass': '',
    # genshinstat
    "ltuid": 12345678,
    "ltoken": "",
    # postgres link
    "StatUri": "",
}

# admin's roles uid
adminRoles = (
)

# ignore chance for the reactions. check def chance (IntReactions.functions)
ignorechance = []

# name of non nsfw list
nonhornylist = []

# for cards
banners = [
    "новый мир",
    "ловец ветра",
    "барон зайчик",
    "бомбочка",
    "огненная птица",
    "дух волка",
    "небесная лира",
    "одуванчики",
    "мелодия",
    "павлин",
    "пески времени",
    "воздушный дух",
    "вестник ночи",
    "щит",
    "звёздная гладь",
    "одобрение",
    "горячий гоба",
    "мечи дождя",
    "вестник стужи",
    "громовой стилет",
    "исследователь",
    "профессионал",
    "герой",
    "песнь ветра",
    "каменный покой",
    "цвета радуги",
    "мастер лучник",
    "испытания",
    "глубины бездны",
    "горный житель",
    "вечный холод",
    "неожиданный поворот",
    "долгожданная встреча",
    "величие феникса",
    "якорь",
    "духовные лезвия",
    "испытания ii",
    "погасшая звезда",
    "мяу-мяу!",
    "падение кометы",
    "музыка свободы",
    "маска",
    "почётный рыцарь",
    "молитва",
    "паруса",
    "среди облаков",
    "испытания iii",
    "снежный пик",
    "цилинь",
    "цветок солнца",
    "мел",
    "древнее дерево",
    "гипостазис",
    "маска якса",
    "упокоение духов",
    "лунный фонарь",
    "свет фонаря",
    "механикус",
    "каторга",
    "анемония",
    "великое пиршество",
    "плод мудрости",
    "ку-ку!",
    "справедливость",
    "морозная печать",
    "другая реальность",
    "чайная песня",
    "сияющая чешуя",
    "любование клёном",
    "летний зной",
    "дом отдыха",
    "необъятность",
    "бабах-мяч",
    "песнь битвы",
    "священная сакура",
    "великий храм наруками",
    "эмблема райдэн",
    "герб камисато",
    "врата",
    "преодоление",
    "каменный дракон",
    "пышное цветение",
    "герб кудзё",
    "великолепный расчёт",
    "веер",
    "искры золотой рыбки",
    "мудзи-мудзи дарума",
    "просветление",
    "морская бездна",
    "тэнгу",
    "рассвет",
    "лунная охота",
    "герб сангономии",
    "гвозди",
    "икки",
    "внимательное ухо",
    "пламенный рукав",
    "божественный генерал",
    "перо орла",
    "безмятежный пёс",
    "лицо они",
    "паслён",
    "гребень",
]
colors = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgrey",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "grey",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgreen",
    "lightgray",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
]
